dist: xenial

sudo: false

language: php

services:
  - mysql
  - postgresql

php:
  - 7.1
  - 7.2

env:
  global:
    - CORE_BRANCH=stable14
    - APP_NAME=facerecognition
  matrix:
    - DB=mysql
    - DB=mysql CORE_BRANCH=stable15
    - DB=pgsql
    - DB=pgsql CORE_BRANCH=stable15
    - DB=sqlite
    - DB=sqlite CORE_BRANCH=stable15

before_install:
  - sudo apt-get install npm
  - sudo npm config set strict-ssl false
  - sudo npm install -g handlebars
  - make
  - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh;
  - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
  - cd ../server;
  - ./occ app:enable $APP_NAME

before_script:
  - ./occ app:check-code $APP_NAME || true
  - cd apps/$APP_NAME

script:
  - make test

  # Create coverage report
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml

after_failure:
  - cat ../../data/nextcloud.log

