dist: xenial

sudo: false

language: php

services:
  - mysql
  - postgresql

php:
  - 7.1
  - 7.2

env:
  global:
    - CORE_BRANCH=stable14
    - APP_NAME=facerecognition
  matrix:
    - DB=mysql
    - DB=pgsql
    - DB=sqlite
    - DB=mysql CORE_BRANCH=stable15
    - DB=pgsql CORE_BRANCH=stable15
    - DB=sqlite CORE_BRANCH=stable15
    - DB=mysql CORE_BRANCH=stable16
    - DB=pgsql CORE_BRANCH=stable16
    - DB=sqlite CORE_BRANCH=stable16
    - DB=mysql CORE_BRANCH=stable17
    - DB=pgsql CORE_BRANCH=stable17
    - DB=sqlite CORE_BRANCH=stable17

before_install:
  # Installing pdlib (install dlib from repo and compile pdlib on top of it)
  - sudo sh -c 'echo "deb [trusted=yes] http://repo.delellis.com.ar xenial main" > /etc/apt/sources.list.d/20-pdlib.list'
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 762E3157
  - sudo apt update
  - sudo apt-get install libdlib-dev
  - wget https://github.com/goodspb/pdlib/archive/v1.0.tar.gz
  - tar -xzf v1.0.tar.gz
  - pushd pdlib-1.0
  - phpize
  - ./configure --enable-debug && make && sudo make install
  - echo "extension=pdlib.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - popd

  - sudo apt-get install npm
  - sudo npm config set strict-ssl false
  - sudo npm install -g handlebars
  - make
  - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh;
  - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
  - cd ../server;
  - ./occ app:enable $APP_NAME

before_script:
  - ./occ app:check-code $APP_NAME || true
  - cd apps/$APP_NAME

script:
  - make test

  # Create coverage report
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml

after_failure:
  - cat ../../data/nextcloud.log

